name: directional-arrows
version: '${project.version}'
main: org.kayteam.directionalarrows.DirectionalArrows
api-version: '1.13'
commands:
  directionalarrows:
    description: Main directionalarrows command
